"""Password hashing and opaque secret tokens.

Pure domain — no database, no framework, no I/O. That is not tidiness for its
own sake: it means every property below can be tested directly, and this is the
file where a mistake is a security bug rather than a defect.

Two different problems, deliberately solved differently:

**Passwords** are low-entropy and chosen by people, so they need a *slow* hash
with a per-password salt. Argon2id, per `UPDATE.md` §5.

**Session and reset tokens** are high-entropy and generated by us, so they need
a *fast* hash — SHA-256 — and no salt. Running Argon2 over a 256-bit random
token buys nothing and would put a ~50 ms cost on every authenticated request.
The property that matters is the same in both cases: what is stored cannot be
turned back into what was presented.
"""

from __future__ import annotations

import hashlib
import hmac
import secrets

from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerificationError, VerifyMismatchError

# OWASP's second recommended Argon2id configuration (19 MiB, t=2, p=1). Memory
# cost is the parameter that actually resists GPU attack; iterations mostly buy
# latency. Sized to stay comfortable on a small Railway container — a hasher
# that OOMs the API is a denial of service we built ourselves.
_hasher = PasswordHasher(
    time_cost=2,
    memory_cost=19 * 1024,
    parallelism=1,
    hash_len=32,
    salt_len=16,
)

# 256 bits. Long enough that guessing is not a threat model.
TOKEN_BYTES = 32

# The longest password we will hash. Argon2's cost is independent of input
# length, but reading an unbounded body into a hash function is not free, and
# nobody has a 4 KB password.
MAX_PASSWORD_LENGTH = 1024
MIN_PASSWORD_LENGTH = 12


class PasswordTooShort(ValueError):
    def __init__(self) -> None:
        super().__init__(f"Password must be at least {MIN_PASSWORD_LENGTH} characters")


class PasswordTooLong(ValueError):
    def __init__(self) -> None:
        super().__init__(f"Password must be at most {MAX_PASSWORD_LENGTH} characters")


def hash_password(password: str) -> str:
    """Argon2id. Returns the full encoded hash, parameters included.

    The parameters travel with the hash, which is what makes `needs_rehash`
    possible later without a migration.
    """
    if len(password) < MIN_PASSWORD_LENGTH:
        raise PasswordTooShort
    if len(password) > MAX_PASSWORD_LENGTH:
        raise PasswordTooLong

    return _hasher.hash(password)


def verify_password(password: str, encoded_hash: str | None) -> bool:
    """Constant-ish time verification that never raises on bad input.

    ``encoded_hash`` is ``None`` for a user who signed up through Google and has
    no password. That returns False rather than raising, so the caller has one
    code path — and, importantly, the caller should still have burned the same
    time verifying a dummy hash first (see `verify_dummy_password`), or the
    absence of a password becomes observable through timing.
    """
    if not encoded_hash:
        return False

    try:
        return _hasher.verify(encoded_hash, password)
    except (VerifyMismatchError, VerificationError, InvalidHashError):
        return False


# A real Argon2id hash of a value nobody knows, used to spend the same time on
# a login for an address that does not exist as on one that does. Without it,
# "no such user" returns in microseconds and "wrong password" in ~50 ms, which
# is a free account-enumeration oracle.
_DUMMY_HASH = _hasher.hash(secrets.token_urlsafe(32))


def verify_dummy_password(password: str) -> bool:
    """Always False. Exists only to consume the same time as a real check."""
    try:
        _hasher.verify(_DUMMY_HASH, password)
    except (VerifyMismatchError, VerificationError, InvalidHashError):
        return False
    return False


def needs_rehash(encoded_hash: str) -> bool:
    """True when the hash was made with weaker parameters than we now use.

    Called on successful login, which is the only moment the plaintext is
    available to re-hash with.
    """
    try:
        return _hasher.check_needs_rehash(encoded_hash)
    except InvalidHashError:
        return True


def generate_token() -> str:
    """An opaque, URL-safe secret. Returned to the user exactly once."""
    return secrets.token_urlsafe(TOKEN_BYTES)


def hash_token(token: str) -> bytes:
    """SHA-256 of a token, as raw bytes for a ``bytea`` column.

    Unsalted on purpose. A salt defends against precomputation over a small
    input space; a 256-bit random token has no such space. What this buys is
    that a database dump contains no usable session cookie and no usable reset
    link.
    """
    return hashlib.sha256(token.encode("utf-8")).digest()


def tokens_equal(presented: bytes, stored: bytes) -> bool:
    """Compare digests without leaking their contents through timing."""
    return hmac.compare_digest(presented, stored)
