"""Core tenancy tables and the lead capture table, with RLS from the start.

Revision ID: 001
Revises:
Create Date: 2026-07-27

Hand-written, not autogenerated. Autogenerate produces tables; it does not
produce policies, and a table that arrives without its policy is the exact
failure this migration exists to prevent.

Three rules hold for every tenant-scoped table here and for every one added
later:

1. ``ENABLE`` **and** ``FORCE`` row level security. ``ENABLE`` alone exempts
   the table's owner — which is ``soyl_migrator``, the role that runs this
   file — so without ``FORCE`` the policies are untested in exactly the
   session that created them.
2. The policy reads ``app.tenant_id`` and nothing else. No application-side
   ``WHERE tenant_id = ...`` anywhere, because a second copy of the rule can
   drift from the first.
3. Grants are written per table, deliberately. ``ALTER DEFAULT PRIVILEGES``
   would be less typing and would silently grant ``soyl_app`` access to the
   next table someone adds without a policy on it.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Every table below is keyed on this. NULLIF guards the case where the setting
# exists but is empty: ''::uuid raises, and a health-check-shaped request
# should not be able to turn a missing setting into a 500.
TENANT_PREDICATE = "(tenant_id = NULLIF(current_setting('app.tenant_id', TRUE), '')::uuid)"
TENANT_SELF_PREDICATE = "(id = NULLIF(current_setting('app.tenant_id', TRUE), '')::uuid)"

APP_ROLE = "soyl_app"

# Tenant-scoped tables in core: (table, predicate).
TENANT_SCOPED: tuple[tuple[str, str], ...] = (
    ("tenant", TENANT_SELF_PREDICATE),
    ("property", TENANT_PREDICATE),
    ("membership", TENANT_PREDICATE),
    ("membership_property", TENANT_PREDICATE),
)


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS core")

    op.create_table(
        "tenant",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.Text(), server_default="Asia/Kolkata", nullable=False),
        sa.Column("base_currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("fiscal_year_start_month", sa.Integer(), server_default="4", nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("settings", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "fiscal_year_start_month BETWEEN 1 AND 12",
            name="ck_tenant_fiscal_year_start_month_is_a_month",
        ),
        sa.CheckConstraint("status IN ('active', 'suspended')", name="ck_tenant_status_is_known"),
        sa.PrimaryKeyConstraint("id", name="pk_tenant"),
        sa.UniqueConstraint("slug", name="uq_tenant_slug"),
        schema="core",
    )

    op.create_table(
        "user_account",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locale", sa.Text(), server_default="en", nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'suspended')", name="ck_user_account_status_is_known"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_user_account"),
        sa.UniqueConstraint("email", name="uq_user_account_email"),
        schema="core",
        comment=(
            "A person, not a tenant member. Deliberately NOT tenant-scoped and "
            "has no RLS policy: a user may hold memberships in several tenants, "
            "and login resolves a user by email before any tenant is known. "
            "Tenancy lives on core.membership. See docs/phase-0/DECISION-LOG.md."
        ),
    )

    op.create_table(
        "property",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Text(), server_default="Asia/Kolkata", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("rooms_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rooms_sellable", sa.Integer(), nullable=True),
        sa.Column("segment", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("rooms_total >= 0", name="ck_property_rooms_total_is_not_negative"),
        sa.CheckConstraint(
            "rooms_sellable IS NULL OR rooms_sellable <= rooms_total",
            name="ck_property_rooms_sellable_fits_in_rooms_total",
        ),
        sa.CheckConstraint("status IN ('active', 'inactive')", name="ck_property_status_is_known"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["core.tenant.id"],
            name="fk_property_tenant_id_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_property"),
        schema="core",
    )
    op.create_index(
        "ix_property_tenant_id_active",
        "property",
        ["tenant_id"],
        unique=False,
        schema="core",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    op.create_table(
        "membership",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("property_scope", sa.Text(), server_default="all", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'manager', 'analyst', 'soyl_staff')",
            name="ck_membership_role_is_known",
        ),
        sa.CheckConstraint(
            "property_scope IN ('all', 'selected')",
            name="ck_membership_property_scope_is_known",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["core.tenant.id"],
            name="fk_membership_tenant_id_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core.user_account.id"],
            name="fk_membership_user_id_user_account",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_membership"),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_membership_tenant_id_user_id"),
        schema="core",
    )

    op.create_table(
        "membership_property",
        sa.Column("membership_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=True), nullable=False),
        # Not in UPDATE.md §7. Added so this table is protected by a policy of
        # its own rather than only by the reachability of core.membership.
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["core.membership.id"],
            name="fk_membership_property_membership_id_membership",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["core.property.id"],
            name="fk_membership_property_property_id_property",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["core.tenant.id"],
            name="fk_membership_property_tenant_id_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("membership_id", "property_id", name="pk_membership_property"),
        schema="core",
    )

    op.create_table(
        "lead",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "length(message) BETWEEN 1 AND 5000", name="ck_lead_message_is_bounded"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_lead"),
        schema="public",
        comment=(
            "Contact-form submissions. NOT tenant-scoped and has no RLS policy "
            "by design: a lead arrives from a stranger before any tenant exists, "
            "so tenant_id here would be a column that is always null. Do not add "
            "one. See docs/phase-0/DECISION-LOG.md."
        ),
    )
    op.execute("CREATE INDEX ix_lead_created_at ON public.lead (created_at DESC)")

    # ── Row-level security ──────────────────────────────────────────────────
    for table, predicate in TENANT_SCOPED:
        op.execute(f"ALTER TABLE core.{table} ENABLE ROW LEVEL SECURITY")
        # FORCE applies the policy to the table's owner too. Without it,
        # soyl_migrator — and anything that ever runs as it — sees everything.
        op.execute(f"ALTER TABLE core.{table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON core.{table} "
            f"FOR ALL USING {predicate} WITH CHECK {predicate}"
        )

    # ── Grants ──────────────────────────────────────────────────────────────
    op.execute(f"GRANT USAGE ON SCHEMA core TO {APP_ROLE}")
    for table, _ in TENANT_SCOPED:
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON core.{table} TO {APP_ROLE}")

    # Not tenant-scoped, so access is bounded by grant rather than by policy.
    # The application may read and update a user; it may not delete one.
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON core.user_account TO {APP_ROLE}")

    # Leads are written by the marketing site and read by the M6 admin screen.
    # No UPDATE and no DELETE: a lead is a record of something that happened.
    op.execute(f"GRANT SELECT, INSERT ON public.lead TO {APP_ROLE}")


def downgrade() -> None:
    op.execute("REVOKE ALL ON public.lead FROM soyl_app")
    op.execute("DROP TABLE public.lead")

    op.drop_table("membership_property", schema="core")
    op.drop_table("membership", schema="core")
    op.drop_index("ix_property_tenant_id_active", table_name="property", schema="core")
    op.drop_table("property", schema="core")
    op.drop_table("user_account", schema="core")
    op.drop_table("tenant", schema="core")
    op.execute("DROP SCHEMA IF EXISTS core CASCADE")
