"""Conversations, turns, envelopes, retrieval logs and feedback.

Revision ID: 006
Revises: 005
Create Date: 2026-07-29

`UPDATE.md` §7's `ai` schema. Two of these tables are called out as
non-negotiable and it is worth being explicit about why, because both look
optional right up until the moment they are not.

**`ai.turn` is the permanent question log** (§6.5): *"Every question is logged,
permanently. This is simultaneously the demand data, the eval corpus and the
roadmap input. It is the single most valuable artifact Phase 0 produces."* Note
what that implies — the input is retained even when the answer fails, even when
the question is nonsense, and especially when we returned nothing, because
"what did people ask that we could not answer" is the roadmap.

**`ai.retrieval_log` is not optional** (§7): *"Without it you cannot answer 'why
did it give that answer', which is the question you will be asked most often."*
It stores the fused ranking and the reranker's scores, not merely the chunk ids,
because "we found it and rejected it at 0.20" and "we never found it" are
different failures with different fixes — a distinction the M4 eval run needed
within an hour of existing.

The envelope is a separate table from the turn rather than a column on it. A
turn row is small, hot, and read on every conversation list; an envelope is
kilobytes of JSONB read only when a turn is opened. Keeping them together would
put the large payload on the same pages as the index the list scans.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "006"
down_revision: str | None = "005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "soyl_app"

PREDICATE = "(tenant_id = NULLIF(current_setting('app.tenant_id', TRUE), '')::uuid)"

TENANTED = ("conversation", "turn", "envelope", "retrieval_log", "feedback")


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS ai")

    op.execute(
        """
        CREATE TABLE ai.conversation (
            id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id     uuid        NOT NULL REFERENCES core.tenant(id) ON DELETE CASCADE,
            user_id       uuid        NOT NULL REFERENCES core.user_account(id) ON DELETE CASCADE,
            -- Written from the first turn's question rather than generated by a
            -- model. A title is not worth a model call, and the first question
            -- is what the user will recognise in a list anyway.
            title         text        NULL,
            turn_count    integer     NOT NULL DEFAULT 0,
            last_turn_at  timestamptz NULL,
            created_at    timestamptz NOT NULL DEFAULT now(),
            archived_at   timestamptz NULL,
            deleted_at    timestamptz NULL,
            CONSTRAINT ck_conversation_turn_count_is_not_negative CHECK (turn_count >= 0)
        )
        """
    )
    # The conversation list: most recent activity first, excluding deleted.
    op.execute(
        "CREATE INDEX ix_conversation_tenant_id_last_turn_at "
        "ON ai.conversation (tenant_id, last_turn_at DESC NULLS LAST) "
        "WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE INDEX ix_conversation_user_id_created_at "
        "ON ai.conversation (user_id, created_at DESC) WHERE deleted_at IS NULL"
    )

    op.execute(
        """
        CREATE TABLE ai.turn (
            id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
            conversation_id uuid        NOT NULL
                                        REFERENCES ai.conversation(id) ON DELETE CASCADE,
            tenant_id       uuid        NOT NULL REFERENCES core.tenant(id) ON DELETE CASCADE,
            user_id         uuid        NOT NULL
                                        REFERENCES core.user_account(id) ON DELETE CASCADE,
            -- §6.5: retained permanently, including for turns that failed and
            -- turns we refused. The questions we could not answer are the most
            -- valuable rows in this table.
            input           text        NOT NULL,
            status          text        NOT NULL DEFAULT 'running',
            -- Null while running, and null forever for a turn that failed
            -- before synthesis. A turn without an envelope is a normal record,
            -- not a broken one.
            envelope_id     uuid        NULL,
            trace_id        text        NULL,
            -- Denormalised totals for this turn. The ledger is the source of
            -- truth; this is so a conversation list can show cost without
            -- aggregating a partitioned table per row.
            input_tokens    integer     NOT NULL DEFAULT 0,
            output_tokens   integer     NOT NULL DEFAULT 0,
            cost_inr        numeric(12, 4) NOT NULL DEFAULT 0,
            latency_ms      integer     NULL,
            -- A retry after a dropped connection must not bill twice or answer
            -- twice. Unique per conversation rather than globally, so two
            -- conversations cannot collide on a client-generated value.
            idempotency_key text        NULL,
            started_at      timestamptz NOT NULL DEFAULT now(),
            completed_at    timestamptz NULL,
            CONSTRAINT ck_turn_status_is_known
                CHECK (status IN ('running', 'complete', 'no_evidence', 'refused', 'failed')),
            CONSTRAINT ck_turn_input_is_not_blank CHECK (length(btrim(input)) > 0),
            CONSTRAINT uq_turn_idempotency_key UNIQUE (conversation_id, idempotency_key)
        )
        """
    )
    op.execute(
        "COMMENT ON TABLE ai.turn IS "
        "'UPDATE.md 6.5: every question, permanently. Demand data, eval corpus "
        "and roadmap input in one table. Never prune by age.'"
    )
    op.execute(
        "CREATE INDEX ix_turn_conversation_id_started_at "
        "ON ai.turn (conversation_id, started_at)"
    )
    op.execute(
        "CREATE INDEX ix_turn_tenant_id_started_at ON ai.turn (tenant_id, started_at DESC)"
    )
    # "What did we fail to answer this week" — the roadmap query, so it gets
    # its own partial index rather than scanning every turn ever asked.
    op.execute(
        "CREATE INDEX ix_turn_unanswered ON ai.turn (tenant_id, started_at DESC) "
        "WHERE status IN ('no_evidence', 'refused', 'failed')"
    )

    op.execute(
        """
        CREATE TABLE ai.envelope (
            id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id  uuid        NOT NULL REFERENCES core.tenant(id) ON DELETE CASCADE,
            turn_id    uuid        NOT NULL REFERENCES ai.turn(id) ON DELETE CASCADE,
            -- The schema version the body was written against. §19.2: additive
            -- evolution needs the client to know what it is looking at, and a
            -- body without its version is unreadable the first time we change
            -- the schema.
            version    integer     NOT NULL DEFAULT 1,
            body       jsonb       NOT NULL,
            size_bytes integer     NOT NULL DEFAULT 0,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_envelope_turn_id UNIQUE (turn_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_envelope_tenant_id_created_at ON ai.envelope (tenant_id, created_at DESC)")

    # Added after both tables exist, because they reference each other.
    op.execute(
        "ALTER TABLE ai.turn ADD CONSTRAINT fk_turn_envelope_id "
        "FOREIGN KEY (envelope_id) REFERENCES ai.envelope(id) ON DELETE SET NULL"
    )

    op.execute(
        """
        CREATE TABLE ai.retrieval_log (
            id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
            turn_id     uuid        NOT NULL REFERENCES ai.turn(id) ON DELETE CASCADE,
            tenant_id   uuid        NOT NULL REFERENCES core.tenant(id) ON DELETE CASCADE,
            query       text        NOT NULL,
            -- Property scope, doc types, validity window: whatever narrowed the
            -- search. A retrieval that found nothing is usually explained by a
            -- filter, and without them the log says "we searched and found
            -- nothing" without saying where we searched.
            filters     jsonb       NOT NULL DEFAULT '{}'::jsonb,
            chunk_ids   uuid[]      NOT NULL DEFAULT '{}',
            scores      real[]      NOT NULL DEFAULT '{}',
            -- Chunks the reranker scored and the threshold rejected. The M4
            -- eval needed this within an hour of existing: "we found it and
            -- scored it 0.20" and "we never found it" are different failures
            -- with different fixes, and from outside both are an empty answer.
            rejected_ids    uuid[]  NOT NULL DEFAULT '{}',
            rejected_scores real[]  NOT NULL DEFAULT '{}',
            -- False when the reranker was absent, too slow or failing, and the
            -- fusion order was used instead (45.3). A quality regression
            -- nobody can account for is usually this, unrecorded.
            reranked    boolean     NOT NULL DEFAULT false,
            latency_ms  integer     NULL,
            created_at  timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_retrieval_log_scores_align
                CHECK (cardinality(chunk_ids) = cardinality(scores)),
            CONSTRAINT ck_retrieval_log_rejected_align
                CHECK (cardinality(rejected_ids) = cardinality(rejected_scores))
        )
        """
    )
    op.execute(
        "COMMENT ON TABLE ai.retrieval_log IS "
        "'UPDATE.md 7: not optional. Without it you cannot answer why did it "
        "give that answer, which is the question you will be asked most often.'"
    )
    op.execute("CREATE INDEX ix_retrieval_log_turn_id ON ai.retrieval_log (turn_id)")
    op.execute(
        "CREATE INDEX ix_retrieval_log_tenant_id_created_at "
        "ON ai.retrieval_log (tenant_id, created_at DESC)"
    )

    op.execute(
        """
        CREATE TABLE ai.feedback (
            id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id   uuid        NOT NULL REFERENCES core.tenant(id) ON DELETE CASCADE,
            user_id     uuid        NOT NULL
                                    REFERENCES core.user_account(id) ON DELETE CASCADE,
            -- A whole answer, or one block of it. Block-level is the useful
            -- grain: "the checklist was right but the citation was wrong" is
            -- actionable in a way that a thumbs-down on the turn is not.
            target_kind text        NOT NULL,
            target_id   text        NOT NULL,
            envelope_id uuid        NULL REFERENCES ai.envelope(id) ON DELETE CASCADE,
            signal      text        NOT NULL,
            reasons     text[]      NOT NULL DEFAULT '{}',
            -- What the answer should have said. The single highest-value field
            -- here: a correction is a labelled eval example someone typed for
            -- us voluntarily.
            correction  text        NULL,
            created_at  timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_feedback_target_kind_is_known
                CHECK (target_kind IN ('turn', 'block')),
            CONSTRAINT ck_feedback_signal_is_known
                CHECK (signal IN ('up', 'down', 'correction'))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_feedback_envelope_id ON ai.feedback (envelope_id) "
        "WHERE envelope_id IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX ix_feedback_tenant_id_created_at "
        "ON ai.feedback (tenant_id, created_at DESC)"
    )

    for table in TENANTED:
        op.execute(f"ALTER TABLE ai.{table} ENABLE ROW LEVEL SECURITY")
        # FORCE as well as ENABLE, so the owner is subject to it too. Migration
        # 001's reasoning applies unchanged: without FORCE, soyl_migrator reads
        # every tenant and the isolation suite passes while proving nothing.
        op.execute(f"ALTER TABLE ai.{table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON ai.{table} "
            f"FOR ALL USING {PREDICATE} WITH CHECK {PREDICATE}"
        )

    op.execute(f"GRANT USAGE ON SCHEMA ai TO {APP_ROLE}")
    op.execute(
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON ai.conversation TO {APP_ROLE}"
    )
    # A turn is updated once, from running to its terminal status. It is never
    # deleted: §6.5 says permanently, and a delete grant is the difference
    # between a log and a cache.
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON ai.turn TO {APP_ROLE}")
    op.execute(f"GRANT SELECT, INSERT ON ai.envelope TO {APP_ROLE}")
    op.execute(f"GRANT SELECT, INSERT ON ai.retrieval_log TO {APP_ROLE}")
    # Feedback is updatable so a user can change their mind, and deletable
    # because it is their own contribution to withdraw.
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON ai.feedback TO {APP_ROLE}")


def downgrade() -> None:
    # Dropped before the tables so the grants do not outlive what they point at.
    for table in TENANTED:
        op.execute(f"REVOKE ALL ON ai.{table} FROM {APP_ROLE}")

    op.execute("ALTER TABLE ai.turn DROP CONSTRAINT IF EXISTS fk_turn_envelope_id")
    op.execute("DROP TABLE IF EXISTS ai.feedback CASCADE")
    op.execute("DROP TABLE IF EXISTS ai.retrieval_log CASCADE")
    op.execute("DROP TABLE IF EXISTS ai.envelope CASCADE")
    op.execute("DROP TABLE IF EXISTS ai.turn CASCADE")
    op.execute("DROP TABLE IF EXISTS ai.conversation CASCADE")
    op.execute("DROP SCHEMA IF EXISTS ai CASCADE")
